export const PruebaPermissionsConfig = {
  'ArchivosAdjuntosResolver.getArchivosAdjuntos_ByRegistroId': [],
  'ArchivosAdjuntosResolver.getFiles_DeRegistro': [],
  'ArchivosAdjuntosResolver.saveFiles_DeRegistro': [],
  'ArchivosController.deleteFile': [],
  'ArchivosController.deleteFilePerfil': [],
  'ArchivosController.seeUploadedFile': [],
  'ArchivosController.seeUploadedFilePerfil': [],
  'ArchivosController.seeUploadedFilePublic': [],
  'ArchivosController.uploadedFile': [],
  'ArchivosController.uploadedFilePerfil': [],
  'AuthController.authGoogle': [],
  'AuthController.changeRole': [],
  'AuthController.googleRegisterOrLogin': [],
  'AuthController.loginWithEmailAndPassword': [],
  'AuthController.loginWithEmailAndPasswordAdmin': [],
  'AuthController.refreshToken': [],
  'AuthController.refreshTokenAdmin': [],
  'AuthController.refreshTokenLogout': [],
  'AuthController.refreshTokenLogoutAdmin': [],
  'CredencialesResolver.createAccountUser': [],
  'CredencialesResolver.generateHash': [],
  'CredencialesResolver.insertCredencial': [],
  'CredencialesResolver.updateCredentials': [],
  'CredencialesResolver.updatePasswordUser': [],
  'CredencialesResolver.verifyToken': [],
  'PaisesResolver.getAllPaises': [],
  'PaisesResolver.getPais_ByName': [],
  'PermisosResolver.deletePermiso': [],
  'PermisosResolver.getPermiso_ById': [],
  'PermisosResolver.getPermisos': [],
  'PermisosResolver.getPermisos_Codigo': [],
  'PermisosResolver.insertPermiso': [],
  'PermisosResolver.updatePermiso': [],
  'PersonaPermisosPersonalizadoResolver.getPermisosPersonalizados_ByPersonaRolId': [],
  'PersonaPermisosPersonalizadoResolver.insertManyPersonaPermisosPersonalizado': [],
  'PersonasResolver.confirmCode': [],
  'PersonasResolver.getPersona_ById': [],
  'PersonasResolver.getPersonas': [],
  'PersonasResolver.getPersonasByEmail': [],
  'PersonasResolver.getPesona_ByToken': [],
  'PersonasResolver.insertPersona': [],
  'PersonasResolver.removePersona': [],
  'PersonasResolver.sendLinkRecoveryAccount': [],
  'PersonasResolver.updatePersona': [],
  'PersonasResolver.updateProfile': [],
  'PersonasResolver.verifyTokenRecovery': [],
  'PersonasRolesResolver.deletePersonaRol': [],
  'PersonasRolesResolver.getPermisos_ByPersonaAndRol': [],
  'PersonasRolesResolver.getPersonasRoles': [],
  'PersonasRolesResolver.insertPersonaRol': [],
  'RolesPermisosResolver.deleteRolPermiso': [],
  'RolesPermisosResolver.getRolPermiso_ById': [],
  'RolesPermisosResolver.getRolPermiso_ByRolId': [],
  'RolesPermisosResolver.getRolesPermisos': [],
  'RolesPermisosResolver.insertRolPermiso': [],
  'RolesPermisosResolver.updateRolPermiso': [],
  'RolesResolver.deleteRol': [],
  'RolesResolver.getRol_ById': [],
  'RolesResolver.getRoles': [],
  'RolesResolver.insertRol': [],
  'RolesResolver.updateRol': [],
};

export const MethodNames = [
  'authGoogle',
  'changeRole',
  'confirmCode',
  'createAccountUser',
  'deleteFile',
  'deleteFilePerfil',
  'deletePermiso',
  'deletePersonaRol',
  'deleteRol',
  'deleteRolPermiso',
  'generateHash',
  'getAllPaises',
  'getArchivosAdjuntos_ByRegistroId',
  'getFiles_DeRegistro',
  'getPais_ByName',
  'getPermiso_ById',
  'getPermisos',
  'getPermisosPersonalizados_ByPersonaRolId',
  'getPermisos_ByPersonaAndRol',
  'getPermisos_Codigo',
  'getPersona_ById',
  'getPersonas',
  'getPersonasByEmail',
  'getPersonasRoles',
  'getPesona_ByToken',
  'getRolPermiso_ById',
  'getRolPermiso_ByRolId',
  'getRol_ById',
  'getRoles',
  'getRolesPermisos',
  'googleRegisterOrLogin',
  'insertCredencial',
  'insertManyPersonaPermisosPersonalizado',
  'insertPermiso',
  'insertPersona',
  'insertPersonaRol',
  'insertRol',
  'insertRolPermiso',
  'loginWithEmailAndPassword',
  'loginWithEmailAndPasswordAdmin',
  'refreshToken',
  'refreshTokenAdmin',
  'refreshTokenLogout',
  'refreshTokenLogoutAdmin',
  'removePersona',
  'saveFiles_DeRegistro',
  'seeUploadedFile',
  'seeUploadedFilePerfil',
  'seeUploadedFilePublic',
  'sendLinkRecoveryAccount',
  'updateCredentials',
  'updatePasswordUser',
  'updatePermiso',
  'updatePersona',
  'updateProfile',
  'updateRol',
  'updateRolPermiso',
  'uploadedFile',
  'uploadedFilePerfil',
  'verifyToken',
  'verifyTokenRecovery',
];
